const CROPS={wheat:{name:'Wheat',potential:16,price:2400,cost:24000,water:450,ky:1.15,wSens:.8,dSens:1.2},rice:{name:'Rice',potential:22,price:2300,cost:32000,water:1200,ky:1.09,wSens:.9,dSens:.7},maize:{name:'Maize',potential:24,price:2100,cost:30000,water:600,ky:1.25,wSens:.9,dSens:.8},sugarcane:{name:'Sugarcane',potential:320,price:350,cost:85000,water:1800,ky:1.2,wSens:.7,dSens:.5},soybean:{name:'Soybean',potential:8,price:4600,cost:21000,water:450,ky:.85,wSens:1,dSens:1},cotton:{name:'Cotton',potential:8,price:7000,cost:34000,water:700,ky:.85,wSens:1,dSens:.9}};
const WEATHER={good:{etm:.95,effect:.03,risk:10},normal:{etm:1,effect:0,risk:30},poor:{etm:1.1,effect:-.1,risk:75}};
const IRRIGATION={flood:{eff:1,cost:0},sprinkler:{eff:1.2,cost:2500},drip:{eff:1.4,cost:5000}};
const PROFILES={balanced:{yield:.35,profit:.3,safety:.35},profit:{yield:.25,profit:.5,safety:.25},safe:{yield:.2,profit:.2,safety:.6}};
const PRESETS={A:{name:'A · Normal',crop:'wheat',area:5,waterPct:100,weather:'normal',timing:'ontime',delayDays:0,costIndex:1,irrigation:'flood',profile:'balanced'},B:{name:'B · Water stress',crop:'wheat',area:5,waterPct:70,weather:'normal',timing:'ontime',delayDays:0,costIndex:1,irrigation:'flood',profile:'balanced'},C:{name:'C · Delayed & costly',crop:'wheat',area:5,waterPct:70,weather:'poor',timing:'delayed',delayDays:14,costIndex:1.25,irrigation:'flood',profile:'balanced'},D:{name:'D · Smart adaptation',crop:'wheat',area:5,waterPct:70,weather:'poor',timing:'ontime',delayDays:0,costIndex:1.1,irrigation:'drip',profile:'balanced'}};
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(n),money=n=>`${n<0?'−':''}₹${fmt(Math.abs(n))}`;
let chosenWeather='normal',chosenTiming='ontime',saved=JSON.parse(localStorage.getItem('prarambha-scenarios')||'[]'),profitChart,riskChart;

function clamp(x,lo,hi){return Math.max(lo,Math.min(hi,x))}
function simulate(s){const c=CROPS[s.crop],w=WEATHER[s.weather],ir=IRRIGATION[s.irrigation],sw=PROFILES[s.profile];const delay=s.timing==='early'?-7:s.timing==='delayed'?Number(s.delayDays):0;const ratio=clamp((s.waterPct/100*ir.eff)/w.etm,0,1);const ryWater=Math.max(.15,1-c.ky*(1-ratio)),fWeather=1+c.wSens*w.effect,fPlant=delay<0?.98:Math.max(.5,1-delay*.007*c.dSens);const yieldPerAcre=c.potential*ryWater*fWeather*fPlant,totalYield=yieldPerAcre*s.area,cost=(c.cost*s.costIndex+ir.cost)*s.area,revenue=totalYield*c.price,profit=revenue-cost,roi=profit/cost,waterMm=c.water*Math.min(s.waterPct/100,w.etm/ir.eff),waterM3=waterMm*4.047*s.area,waterProd=waterM3?totalYield*100/waterM3:0;const riskParts={water:Math.min(100,200*(1-ratio)),weather:w.risk,planting:delay>0?Math.min(100,10+delay*3.5*c.dSens):delay<0?30:10,financial:clamp(100*(1-roi/.8),0,100)};const risk=.35*riskParts.water+.2*riskParts.weather+.2*riskParts.planting+.25*riskParts.financial;const level=risk<35?'Low':risk<65?'Medium':'High',yIdx=100*yieldPerAcre/c.potential,pIdx=clamp(100*roi/.8,0,100),score=sw.yield*yIdx+sw.profit*pIdx+sw.safety*(100-risk),band=.08+.2*risk/100;return{...s,cropName:c.name,totalYield,cost,revenue,profit,roi,waterM3,waterProd,risk,riskParts,level,score,yieldLow:totalYield*(1-band),yieldHigh:totalYield*(1+band)}}
function getForm(){return{name:$('name').value.trim()||'My farm plan',crop:$('crop').value,area:Number($('area').value)||5,waterPct:Number($('waterPct').value),weather:chosenWeather,timing:chosenTiming,delayDays:Number($('delayDays').value),costIndex:Number($('costIndex').value),irrigation:$('irrigation').value,profile:$('profile').value}}
let current=simulate(getForm());
function verdict(r){if(r.profit<0)return ['NOT RECOMMENDED','This plan is likely to lose money.','Try reducing water risk, sowing on time, or lowering input costs.'];if(r.risk>=65)return ['HIGH RISK','A positive return faces substantial pressure.','Compare an adaptation before committing resources.'];if(r.risk>=35)return ['MARGINAL','The plan can work, but is sensitive to the season.','Protect your margin with water and input planning.'];return ['RECOMMENDED','A solid starting plan.','Conditions support a positive return with low overall risk.']}
function renderCurrent(){current=simulate(getForm());const r=current,[tag,title,text]=verdict(r);$('resultName').textContent=r.name;$('profit').textContent=money(r.profit);$('profit').style.color=r.profit<0?'var(--red)':'';$('yield').textContent=`${r.totalYield.toFixed(1)} q`;$('yieldRange').textContent=`range ${r.yieldLow.toFixed(0)} – ${r.yieldHigh.toFixed(0)} q`;$('water').textContent=`${fmt(r.waterM3)} m³`;$('waterProductivity').textContent=`${r.waterProd.toFixed(2)} kg per m³`;$('score').textContent=Math.round(r.score);$('cost').textContent=money(r.cost);$('revenue').textContent=money(r.revenue);$('roi').textContent=`${Math.round(r.roi*100)}%`;$('risk').textContent=`${Math.round(r.risk)} / 100`;$('riskPill').textContent=`${r.level.toUpperCase()} RISK`;$('riskPill').className=`risk-pill ${r.level.toLowerCase()}`;$('verdictLabel').textContent=tag;$('verdict').textContent=title;$('verdictText').textContent=text}
function setSegment(id,value){document.querySelectorAll(`#${id} button`).forEach(b=>b.classList.toggle('selected',b.dataset.value===value))}
function fillForm(s){$('name').value=s.name;$('crop').value=s.crop;$('area').value=s.area;$('waterPct').value=s.waterPct;$('costIndex').value=s.costIndex;$('irrigation').value=s.irrigation;$('profile').value=s.profile;$('delayDays').value=s.delayDays||14;chosenWeather=s.weather;chosenTiming=s.timing;setSegment('weather',chosenWeather);setSegment('timing',chosenTiming);$('delayWrap').classList.toggle('hidden',chosenTiming!=='delayed');syncOutputs();renderCurrent()}
function syncOutputs(){$('waterOutput').textContent=`${$('waterPct').value}%`;$('costOutput').textContent=`${Number($('costIndex').value).toFixed(2)}× normal`;$('delayOutput').textContent=`${$('delayDays').value} days`}
function saveCurrent(){const item={...current,id:crypto.randomUUID()};const index=saved.findIndex(x=>x.name===item.name);if(index>=0)saved[index]=item;else {if(saved.length>=4)saved.shift();saved.push(item)};persist();renderSaved()}
function persist(){localStorage.setItem('prarambha-scenarios',JSON.stringify(saved))}
function renderSaved(){const cards=$('scenarioCards'),empty=$('emptyComparison');cards.innerHTML='';empty.classList.toggle('hidden',saved.length>0);saved.forEach((r,i)=>{cards.insertAdjacentHTML('beforeend',`<article class="scenario-card"><button data-remove="${r.id}" aria-label="Remove ${r.name}">×</button><small>${i===0?'REFERENCE':'SAVED PLAN'}</small><h3>${r.name}</h3><strong>${money(r.profit)}</strong><br><span>${r.totalYield.toFixed(1)} q · ${r.level} risk</span></article>`)});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{saved=saved.filter(x=>x.id!==b.dataset.remove);persist();renderSaved()});renderTable();renderCharts();renderWhy()}
function renderTable(){const metrics=[['Estimated profit',r=>money(r.profit),'high'],['Estimated yield',r=>`${r.totalYield.toFixed(1)} q`,'high'],['Water drawn',r=>`${fmt(r.waterM3)} m³`,'low'],['Water productivity',r=>`${r.waterProd.toFixed(2)} kg/m³`,'high'],['Risk score',r=>`${Math.round(r.risk)} · ${r.level}`,'low'],['Decision score',r=>Math.round(r.score),'high']];for(let i=0;i<4;i++)$(`head${i}`).textContent=saved[i]?.name||'—';$('comparisonBody').innerHTML=metrics.map(([label,get,direction])=>{const values=saved.map(get),nums=saved.map(r=>label==='Estimated profit'?r.profit:label==='Estimated yield'?r.totalYield:label==='Water drawn'?r.waterM3:label==='Water productivity'?r.waterProd:label==='Risk score'?r.risk:r.score);const best=nums.length?(direction==='low'?Math.min(...nums):Math.max(...nums)):null;return `<tr><td>${label}</td>${[0,1,2,3].map(i=>`<td class="${nums[i]===best&&saved.length>1?'best':''}">${values[i]??'—'}</td>`).join('')}</tr>`}).join('')}
function renderCharts(){
  if(profitChart)profitChart.destroy();
  if(riskChart)riskChart.destroy();
  if(!saved.length)return;
  const labels=saved.map(x=>x.name),colors=saved.map(x=>x.profit>=0?'#4d7c43':'#c8514b');
  profitChart=new Chart($('profitChart'),{
    type:'bar', data:{labels,datasets:[{data:saved.map(x=>x.profit),backgroundColor:colors,borderRadius:5}]},
    options:{plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>money(c.raw)}}},scales:{y:{ticks:{callback:v=>'₹'+(v/1000)+'k'},grid:{color:'#e7ebdf'}},x:{grid:{display:false}}}}
  });
  riskChart=new Chart($('riskChart'),{
    type:'radar',
    data:{labels:['Water','Weather','Planting','Financial'],datasets:saved.map((x,i)=>({label:x.name,data:Object.values(x.riskParts),borderColor:['#284f3d','#d0922b','#a0514a','#688a3b'][i],backgroundColor:['#284f3d18','#d0922b18','#a0514a18','#688a3b18'][i],pointRadius:2}))},
    options:{plugins:{legend:{position:'bottom',labels:{boxWidth:10,font:{size:10}}}},scales:{r:{min:0,max:100,ticks:{display:false},pointLabels:{font:{size:11}},grid:{color:'#dbe2d8'}}}}
  });
}
function renderWhy(){const select=$('baselineSelect');select.innerHTML=saved.map((x,i)=>`<option value="${i}">${x.name}</option>`).join('');const base=saved[Number(select.value)||0],alt=saved.find((x,i)=>i!==(Number(select.value)||0));if(!base||!alt){$('whyTitle').textContent='Save two scenarios to compare';$('whyTotal').textContent='—';$('drivers').innerHTML='<p class="muted">Once you save a baseline and an alternative, you will see an explainable breakdown here.</p>';$('recommendations').innerHTML='';return}const entries=[['Water availability',alt.riskParts.water-base.riskParts.water],['Weather',alt.riskParts.weather-base.riskParts.weather],['Planting timing',alt.riskParts.planting-base.riskParts.planting],['Input & irrigation',Math.max(0,(alt.cost-base.cost)/Math.max(base.cost,1)*100)]];const change=alt.profit-base.profit,max=Math.max(...entries.map(x=>Math.abs(x[1])),1);$('whyTitle').textContent=`${base.name} → ${alt.name}`;$('whyTotal').textContent=`${change>=0?'+':''}${money(change)}`;$('drivers').innerHTML=entries.map(([n,v])=>`<div class="driver ${v>0?'negative':''}"><span>${n}</span><div class="bar"><i style="width:${Math.abs(v)/max*100}%"></i></div><b>${v>=0?'+':''}${Math.round(v)} risk pts</b></div>`).join('');const advice=[];if(alt.riskParts.water>=50)advice.push('Consider drip or sprinkler irrigation and prioritise critical growth stages.');if(alt.timing==='delayed')advice.push('Advance sowing where possible; planting delay is adding avoidable risk.');if(alt.costIndex>1.15)advice.push('Explore FPO group-buying or pre-booking inputs to protect the margin.');if(alt.profit<0)advice.push('Do not proceed as configured; compare a lower-risk alternative first.');if(!advice.length)advice.push('This plan is stable. Preserve the water and cost conditions that keep risk low.');$('recommendations').innerHTML=`<h4>RECOMMENDED NEXT STEP</h4><ul>${advice.map(x=>`<li>${x}</li>`).join('')}</ul>`}
document.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',()=>{syncOutputs();renderCurrent()}));document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{if(b.closest('#weather')){chosenWeather=b.dataset.value;setSegment('weather',chosenWeather)}else{chosenTiming=b.dataset.value;setSegment('timing',chosenTiming);$('delayWrap').classList.toggle('hidden',chosenTiming!=='delayed')}renderCurrent()});$('scenarioForm').onsubmit=e=>{e.preventDefault();renderCurrent()};$('saveScenario').onclick=saveCurrent;$('clearSaved').onclick=()=>{saved=[];persist();renderSaved()};$('loadDemo').onclick=()=>{saved=Object.values(PRESETS).map(s=>({...simulate(s),id:crypto.randomUUID()}));persist();renderSaved();location.hash='compare'};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>fillForm(PRESETS[b.dataset.preset]));$('baselineSelect').onchange=renderWhy;syncOutputs();renderCurrent();renderSaved();
